import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, X } from "lucide-react";
import { PageHero } from "@/components/site/PageHero";

const COMPARE = [
  { topic: "Treatment planning", us: "Designed personally by Dr. Tsai for each patient", them: "Templated plans, often generated by aligner software" },
  { topic: "Who you see at each visit", us: "Dr. Tsai, every appointment", them: "Rotating associates or technicians" },
  { topic: "First consultation", us: "Unhurried conversation, complimentary, no obligation", them: "Sales-driven exam designed to close" },
  { topic: "Treatment philosophy", us: "Considered, conservative, airway-aware", them: "Production-focused, often extraction-default" },
  { topic: "Practice atmosphere", us: "Quiet boutique, residential warmth", them: "High-volume clinic, fluorescent lighting" },
  { topic: "Communication", us: "Direct line to Dr. Tsai's team in English or Mandarin", them: "Call centre or generic patient portal" },
  { topic: "Long-term care", us: "Retention and follow-up for life", them: "Discharged shortly after treatment ends" },
];

export const Route = createFileRoute("/what-sets-us-apart")({
  head: () => ({
    meta: [
      { title: "What Sets Us Apart — Tsai Orthodontics" },
      {
        name: "description",
        content:
          "Specialist-led, family-centred orthodontic care in Vancouver. See how our boutique practice compares to a typical orthodontic clinic.",
      },
      { property: "og:title", content: "What Sets Tsai Orthodontics Apart" },
      { property: "og:description", content: "A boutique, specialist-led orthodontic practice that competes on quality of care, not on price." },
      { property: "og:url", content: "/what-sets-us-apart" },
    ],
    links: [{ rel: "canonical", href: "/what-sets-us-apart" }],
  }),
  component: Page,
});

function Page() {
  return (
    <>
      <PageHero
        eyebrow="What Sets Us Apart"
        title={<>Quality you can feel <span className="italic font-normal">before you sit in the chair.</span></>}
        intro="We don't compete on price. We compete on the things that decide whether a smile looks naturally beautiful in ten years — specialist judgment, the time we take, and the relationships we keep."
      />

      <section className="px-6 lg:px-10 pb-24 lg:pb-32">
        <div className="max-w-6xl mx-auto rounded-3xl bg-foreground text-background overflow-hidden">
          <div className="grid grid-cols-12 px-6 md:px-10 py-6 border-b border-white/10 text-[10px] uppercase tracking-[0.25em] text-background/50">
            <div className="col-span-4">Consideration</div>
            <div className="col-span-4 text-primary">Tsai Orthodontics</div>
            <div className="col-span-4 text-background/50 hidden md:block">Typical high-volume clinic</div>
          </div>
          {COMPARE.map((row) => (
            <div key={row.topic} className="grid grid-cols-12 px-6 md:px-10 py-7 border-b border-white/5 last:border-b-0 gap-4">
              <div className="col-span-12 md:col-span-4 font-display text-xl md:text-2xl">{row.topic}</div>
              <div className="col-span-12 md:col-span-4 flex gap-3 text-background/90">
                <Check className="size-5 text-primary flex-none mt-0.5" />
                <span>{row.us}</span>
              </div>
              <div className="col-span-12 md:col-span-4 flex gap-3 text-background/50">
                <X className="size-5 text-background/30 flex-none mt-0.5" />
                <span>{row.them}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="px-6 lg:px-10 pb-32">
        <div className="max-w-3xl mx-auto text-center">
          <p className="font-display text-3xl md:text-4xl leading-[1.15] text-balance mb-10">
            Most of our patients tell us, after their consultation, that the visit alone made the difference.
          </p>
          <Link
            to="/contact"
            className="inline-flex items-center justify-center px-8 py-4 rounded-full bg-primary text-primary-foreground text-xs uppercase tracking-[0.2em] hover:bg-foreground transition-colors"
          >
            Book your consultation
          </Link>
        </div>
      </section>
    </>
  );
}
