import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, X } from "lucide-react";
import { PageHero } from "@/components/site/PageHero";
import { useT } from "@/lib/i18n";

interface Row {
  topic: string;
  topicZh: string;
  us: string;
  usZh: string;
  them: string;
  themZh: string;
}

const COMPARE: Row[] = [
  {
    topic: "Treatment planning",
    topicZh: "治療計畫",
    us: "Designed personally by Dr. Tsai for each patient",
    usZh: "每一份計畫皆由 Dr. Tsai 親自為病患設計",
    them: "Templated plans, often generated by aligner software",
    themZh: "套用模板，常由隱形牙套軟體自動產生",
  },
  {
    topic: "Who you see at each visit",
    topicZh: "每次看診的醫師",
    us: "Dr. Tsai, every appointment",
    usZh: "每次回診都由 Dr. Tsai 親自看診",
    them: "Rotating associates or technicians",
    themZh: "由輪值的助理醫師或技術人員處理",
  },
  {
    topic: "First consultation",
    topicZh: "第一次諮詢",
    us: "Unhurried conversation, complimentary, no obligation",
    usZh: "從容的對話，完全免費、毫無壓力",
    them: "Sales-driven exam designed to close",
    themZh: "以成交為目的、偏向銷售導向的檢查",
  },
  {
    topic: "Treatment philosophy",
    topicZh: "治療理念",
    us: "Considered, conservative, airway-aware",
    usZh: "謹慎、保守，並將呼吸道因素納入考量",
    them: "Production-focused, often extraction-default",
    themZh: "以產量為主，常常一律建議拔牙",
  },
  {
    topic: "Practice atmosphere",
    topicZh: "診所氛圍",
    us: "Quiet boutique, residential warmth",
    usZh: "安靜的精品診所，帶著居家般的溫度",
    them: "High-volume clinic, fluorescent lighting",
    themZh: "高人流量、冷白光的診所環境",
  },
  {
    topic: "Communication",
    topicZh: "溝通方式",
    us: "Direct line to Dr. Tsai's team in English or Mandarin",
    usZh: "可直接與 Dr. Tsai 的團隊以英文或國語聯繫",
    them: "Call centre or generic patient portal",
    themZh: "由客服中心或一般病患入口網站處理",
  },
  {
    topic: "Long-term care",
    topicZh: "長期照護",
    us: "Retention and follow-up for life",
    usZh: "提供終身的維持器追蹤與長期照護",
    them: "Discharged shortly after treatment ends",
    themZh: "療程結束後不久即結束追蹤",
  },
];

export const Route = createFileRoute("/what-sets-us-apart")({
  head: () => ({
    meta: [
      { title: "What Sets Us Apart — Tsai Orthodontics" },
      {
        name: "description",
        content:
          "Specialist-led, family-centred orthodontic care in Vancouver. See how our boutique practice compares to a typical orthodontic clinic.",
      },
      { property: "og:title", content: "What Sets Tsai Orthodontics Apart" },
      {
        property: "og:description",
        content:
          "A boutique, specialist-led orthodontic practice that competes on quality of care, not on price.",
      },
      { property: "og:url", content: "/what-sets-us-apart" },
    ],
    links: [{ rel: "canonical", href: "/what-sets-us-apart" }],
  }),
  component: Page,
});

function Page() {
  const { t, lang } = useT();
  return (
    <>
      <PageHero
        eyebrow={t("What Sets Us Apart", "我們的不同之處")}
        title={t(
          <>
            Quality you can feel <span className="italic font-normal">before you sit in the chair.</span>
          </>,
          <>
            在坐上診療椅之前，<span className="italic font-normal">就能感受到的品質。</span>
          </>,
        )}
        intro={t(
          "We don't compete on price. We compete on the things that decide whether a smile looks naturally beautiful in ten years — specialist judgment, the time we take, and the relationships we keep.",
          "我們不以價格競爭。我們在乎的是十年後笑容是否依然自然美觀——專科醫師的判斷、看診時投入的時間，以及長期維繫的醫病關係。",
        )}
      />

      <section className="px-6 lg:px-10 pb-24 lg:pb-32">
        <div className="max-w-6xl mx-auto rounded-3xl bg-foreground text-background overflow-hidden">
          <div className="grid grid-cols-12 px-6 md:px-10 py-6 border-b border-white/10 text-[10px] uppercase tracking-[0.25em] text-background/50">
            <div className="col-span-4">{t("Consideration", "比較項目")}</div>
            <div className="col-span-4 text-primary">Tsai Orthodontics</div>
            <div className="col-span-4 text-background/50 hidden md:block">
              {t("Typical high-volume clinic", "一般高量診所")}
            </div>
          </div>
          {COMPARE.map((row) => (
            <div
              key={row.topic}
              className="grid grid-cols-12 px-6 md:px-10 py-7 border-b border-white/5 last:border-b-0 gap-4"
            >
              <div className="col-span-12 md:col-span-4 font-display text-xl md:text-2xl">
                {lang === "zh" ? row.topicZh : row.topic}
              </div>
              <div className="col-span-12 md:col-span-4 flex gap-3 text-background/90">
                <Check className="size-5 text-primary flex-none mt-0.5" />
                <span>{lang === "zh" ? row.usZh : row.us}</span>
              </div>
              <div className="col-span-12 md:col-span-4 flex gap-3 text-background/50">
                <X className="size-5 text-background/30 flex-none mt-0.5" />
                <span>{lang === "zh" ? row.themZh : row.them}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="px-6 lg:px-10 pb-32">
        <div className="max-w-3xl mx-auto text-center">
          <p className="font-display text-3xl md:text-4xl leading-[1.15] text-balance mb-10">
            {t(
              "Most of our patients tell us, after their consultation, that the visit alone made the difference.",
              "許多病患在諮詢結束後告訴我們，光是這一次看診的體驗，就足以讓他們做出決定。",
            )}
          </p>
          <Link
            to="/contact"
            className="inline-flex items-center justify-center px-8 py-4 rounded-full bg-primary text-primary-foreground text-xs uppercase tracking-[0.2em] hover:bg-foreground transition-colors"
          >
            {t("Book your consultation", "預約諮詢")}
          </Link>
        </div>
      </section>
    </>
  );
}
