/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatSetsUsApartRouteImport } from './routes/what-sets-us-apart'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NewPatientsRouteImport } from './routes/new-patients'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DentistReferralRouteImport } from './routes/dentist-referral'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutTheDoctorsRouteImport } from './routes/about-the-doctors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutTheDoctorsIndexRouteImport } from './routes/about-the-doctors.index'
import { Route as AboutTheDoctorsDrMarjorieTsaiRouteImport } from './routes/about-the-doctors.dr-marjorie-tsai'
import { Route as AboutTheDoctorsDrAndrewTsaiRouteImport } from './routes/about-the-doctors.dr-andrew-tsai'

const WhatSetsUsApartRoute = WhatSetsUsApartRouteImport.update({
  id: '/what-sets-us-apart',
  path: '/what-sets-us-apart',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientsRoute = NewPatientsRouteImport.update({
  id: '/new-patients',
  path: '/new-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistReferralRoute = DentistReferralRouteImport.update({
  id: '/dentist-referral',
  path: '/dentist-referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTheDoctorsRoute = AboutTheDoctorsRouteImport.update({
  id: '/about-the-doctors',
  path: '/about-the-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTheDoctorsIndexRoute = AboutTheDoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutTheDoctorsRoute,
} as any)
const AboutTheDoctorsDrMarjorieTsaiRoute =
  AboutTheDoctorsDrMarjorieTsaiRouteImport.update({
    id: '/dr-marjorie-tsai',
    path: '/dr-marjorie-tsai',
    getParentRoute: () => AboutTheDoctorsRoute,
  } as any)
const AboutTheDoctorsDrAndrewTsaiRoute =
  AboutTheDoctorsDrAndrewTsaiRouteImport.update({
    id: '/dr-andrew-tsai',
    path: '/dr-andrew-tsai',
    getParentRoute: () => AboutTheDoctorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-the-doctors': typeof AboutTheDoctorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dentist-referral': typeof DentistReferralRoute
  '/faq': typeof FaqRoute
  '/new-patients': typeof NewPatientsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-sets-us-apart': typeof WhatSetsUsApartRoute
  '/about-the-doctors/dr-andrew-tsai': typeof AboutTheDoctorsDrAndrewTsaiRoute
  '/about-the-doctors/dr-marjorie-tsai': typeof AboutTheDoctorsDrMarjorieTsaiRoute
  '/about-the-doctors/': typeof AboutTheDoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dentist-referral': typeof DentistReferralRoute
  '/faq': typeof FaqRoute
  '/new-patients': typeof NewPatientsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-sets-us-apart': typeof WhatSetsUsApartRoute
  '/about-the-doctors/dr-andrew-tsai': typeof AboutTheDoctorsDrAndrewTsaiRoute
  '/about-the-doctors/dr-marjorie-tsai': typeof AboutTheDoctorsDrMarjorieTsaiRoute
  '/about-the-doctors': typeof AboutTheDoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-the-doctors': typeof AboutTheDoctorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/dentist-referral': typeof DentistReferralRoute
  '/faq': typeof FaqRoute
  '/new-patients': typeof NewPatientsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-sets-us-apart': typeof WhatSetsUsApartRoute
  '/about-the-doctors/dr-andrew-tsai': typeof AboutTheDoctorsDrAndrewTsaiRoute
  '/about-the-doctors/dr-marjorie-tsai': typeof AboutTheDoctorsDrMarjorieTsaiRoute
  '/about-the-doctors/': typeof AboutTheDoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-the-doctors'
    | '/contact'
    | '/dentist-referral'
    | '/faq'
    | '/new-patients'
    | '/services'
    | '/sitemap.xml'
    | '/what-sets-us-apart'
    | '/about-the-doctors/dr-andrew-tsai'
    | '/about-the-doctors/dr-marjorie-tsai'
    | '/about-the-doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dentist-referral'
    | '/faq'
    | '/new-patients'
    | '/services'
    | '/sitemap.xml'
    | '/what-sets-us-apart'
    | '/about-the-doctors/dr-andrew-tsai'
    | '/about-the-doctors/dr-marjorie-tsai'
    | '/about-the-doctors'
  id:
    | '__root__'
    | '/'
    | '/about-the-doctors'
    | '/contact'
    | '/dentist-referral'
    | '/faq'
    | '/new-patients'
    | '/services'
    | '/sitemap.xml'
    | '/what-sets-us-apart'
    | '/about-the-doctors/dr-andrew-tsai'
    | '/about-the-doctors/dr-marjorie-tsai'
    | '/about-the-doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutTheDoctorsRoute: typeof AboutTheDoctorsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DentistReferralRoute: typeof DentistReferralRoute
  FaqRoute: typeof FaqRoute
  NewPatientsRoute: typeof NewPatientsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatSetsUsApartRoute: typeof WhatSetsUsApartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-sets-us-apart': {
      id: '/what-sets-us-apart'
      path: '/what-sets-us-apart'
      fullPath: '/what-sets-us-apart'
      preLoaderRoute: typeof WhatSetsUsApartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patients': {
      id: '/new-patients'
      path: '/new-patients'
      fullPath: '/new-patients'
      preLoaderRoute: typeof NewPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist-referral': {
      id: '/dentist-referral'
      path: '/dentist-referral'
      fullPath: '/dentist-referral'
      preLoaderRoute: typeof DentistReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-the-doctors': {
      id: '/about-the-doctors'
      path: '/about-the-doctors'
      fullPath: '/about-the-doctors'
      preLoaderRoute: typeof AboutTheDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-the-doctors/': {
      id: '/about-the-doctors/'
      path: '/'
      fullPath: '/about-the-doctors/'
      preLoaderRoute: typeof AboutTheDoctorsIndexRouteImport
      parentRoute: typeof AboutTheDoctorsRoute
    }
    '/about-the-doctors/dr-marjorie-tsai': {
      id: '/about-the-doctors/dr-marjorie-tsai'
      path: '/dr-marjorie-tsai'
      fullPath: '/about-the-doctors/dr-marjorie-tsai'
      preLoaderRoute: typeof AboutTheDoctorsDrMarjorieTsaiRouteImport
      parentRoute: typeof AboutTheDoctorsRoute
    }
    '/about-the-doctors/dr-andrew-tsai': {
      id: '/about-the-doctors/dr-andrew-tsai'
      path: '/dr-andrew-tsai'
      fullPath: '/about-the-doctors/dr-andrew-tsai'
      preLoaderRoute: typeof AboutTheDoctorsDrAndrewTsaiRouteImport
      parentRoute: typeof AboutTheDoctorsRoute
    }
  }
}

interface AboutTheDoctorsRouteChildren {
  AboutTheDoctorsDrAndrewTsaiRoute: typeof AboutTheDoctorsDrAndrewTsaiRoute
  AboutTheDoctorsDrMarjorieTsaiRoute: typeof AboutTheDoctorsDrMarjorieTsaiRoute
  AboutTheDoctorsIndexRoute: typeof AboutTheDoctorsIndexRoute
}

const AboutTheDoctorsRouteChildren: AboutTheDoctorsRouteChildren = {
  AboutTheDoctorsDrAndrewTsaiRoute: AboutTheDoctorsDrAndrewTsaiRoute,
  AboutTheDoctorsDrMarjorieTsaiRoute: AboutTheDoctorsDrMarjorieTsaiRoute,
  AboutTheDoctorsIndexRoute: AboutTheDoctorsIndexRoute,
}

const AboutTheDoctorsRouteWithChildren = AboutTheDoctorsRoute._addFileChildren(
  AboutTheDoctorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutTheDoctorsRoute: AboutTheDoctorsRouteWithChildren,
  ContactRoute: ContactRoute,
  DentistReferralRoute: DentistReferralRoute,
  FaqRoute: FaqRoute,
  NewPatientsRoute: NewPatientsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatSetsUsApartRoute: WhatSetsUsApartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
